require('rootpath')();
const express = require('express');
const app = express();
const cors = require('cors');
const errorHandler = require('./_middleware/error-handler');
const config = require('./config.json');

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());

// api routes
app.use('/ads', require('./controllers/ads.controller'));
app.use('/advisers', require('./controllers/advisers.controller'));
app.use('/advisers_commissions', require('./controllers/advisers_commissions.controller'));
app.use('/advisers_schedules', require('./controllers/advisers_schedules.controller'));
app.use('/age_groups', require('./controllers/age_groups.controller'));
app.use('/agencies', require('./controllers/agencies.controller'));
app.use('/agencies_commissions', require('./controllers/agencies_commissions.controller'));
app.use('/agencies_ibo', require('./controllers/agencies_ibo.controller'));
app.use('/agencies_ibo_products', require('./controllers/agencies_ibo_products.controller'));
app.use('/authorization_api', require('./controllers/authorization_api.controller'));
app.use('/banners', require('./controllers/banners.controller'));
app.use('/blog_categories', require('./controllers/blog_categories.controller'));
app.use('/blog_tags', require('./controllers/blog_tags.controller'));
app.use('/blogs', require('./controllers/blogs.controller'));
app.use('/campaign_fails', require('./controllers/campaign_fails.controller'));
app.use('/campaign_lists', require('./controllers/campaign_lists.controller'));
app.use('/campaign_send', require('./controllers/campaign_send.controller'));
app.use('/campaigns', require('./controllers/campaigns.controller'));
app.use('/campaigns_push', require('./controllers/campaigns_push.controller'));
app.use('/campaigns_push_details', require('./controllers/campaigns_push_details.controller'));
app.use('/campaigns_push_fails', require('./controllers/campaigns_push_fails.controller'));
app.use('/campaigns_push_lists', require('./controllers/campaigns_push_lists.controller'));
app.use('/campaigns_push_send', require('./controllers/campaigns_push_send.controller'));
app.use('/categories', require('./controllers/categories.controller'));
app.use('/contacts', require('./controllers/contacts.controller'));
app.use('/contracts', require('./controllers/contracts.controller'));
app.use('/countries', require('./controllers/countries.controller'));
app.use('/declaration_age_groups', require('./controllers/declaration_age_groups.controller'));
app.use('/declaration_health', require('./controllers/declaration_health.controller'));
app.use('/declaration_pathology', require('./controllers/declaration_pathology.controller'));
app.use('/downloadable_files', require('./controllers/downloadable_files.controller'));
app.use('/events', require('./controllers/events.controller'));
app.use('/exchange_rate', require('./controllers/exchange_rate.controller'));
app.use('/faqs', require('./controllers/faqs.controller'));
app.use('/fee_insurances', require('./controllers/fee_insurances.controller'));
app.use('/fee_percentages', require('./controllers/fee_percentages.controller'));
app.use('/fee_receipts', require('./controllers/fee_receipts.controller'));
app.use('/fees', require('./controllers/fees.controller'));
app.use('/files', require('./controllers/files.controller'));
app.use('/incident_files', require('./controllers/incident_files.controller'));
app.use('/incident_service', require('./controllers/incident_service.controller'));
app.use('/information', require('./controllers/information.controller'));
app.use('/insurance_beneficiaries', require('./controllers/insurance_beneficiaries.controller'));
app.use('/insurance_beneficiaries_temp', require('./controllers/insurance_beneficiaries_temp.controller'));
app.use('/insurance_buy', require('./controllers/insurance_buy.controller'));
app.use('/insurance_buy_declaration', require('./controllers/insurance_buy_declaration.controller'));
app.use('/insurance_buy_declaration_temp', require('./controllers/insurance_buy_declaration_temp.controller'));
app.use('/insurance_buy_temp', require('./controllers/insurance_buy_temp.controller'));
app.use('/insurance_coupons', require('./controllers/insurance_coupons.controller'));
app.use('/insurance_declaration_health', require('./controllers/insurance_declaration_health.controller'));
app.use('/insurance_declaration_pathology', require('./controllers/insurance_declaration_pathology.controller'));
app.use('/insurance_payment', require('./controllers/insurance_payment.controller'));
app.use('/insurance_payment_temp', require('./controllers/insurance_payment_temp.controller'));
app.use('/insurance_prices', require('./controllers/insurance_prices.controller'));
app.use('/insurance_terms', require('./controllers/insurance_terms.controller'));
app.use('/insurance_visiontravel', require('./controllers/insurance_visiontravel.controller'));
app.use('/insurance_visiontravel_test', require('./controllers/insurance_visiontravel_test.controller'));
app.use('/insurances', require('./controllers/insurances.controller'));
app.use('/lists', require('./controllers/lists.controller'));
app.use('/newsletters', require('./controllers/newsletters.controller'));
app.use('/payment_links', require('./controllers/payment_links.controller'));
app.use('/payment_transactions', require('./controllers/payment_transactions.controller'));
app.use('/price_age_groups', require('./controllers/price_age_groups.controller'));
app.use('/products', require('./controllers/products.controller'));
app.use('/products_files', require('./controllers/products_files.controller'));
app.use('/profiles', require('./controllers/profiles.controller'));
app.use('/quoters', require('./controllers/quoters.controller'));
app.use('/recover_password', require('./controllers/recover_password.controller'));
app.use('/sections', require('./controllers/sections.controller'));
app.use('/services', require('./controllers/services.controller'));
app.use('/session_data', require('./controllers/session_data.controller'));
app.use('/session_data_adviser', require('./controllers/session_data_adviser.controller'));
app.use('/smoker_taxes', require('./controllers/smoker_taxes.controller'));
app.use('/status', require('./controllers/status.controller'));
app.use('/subscriber_lists', require('./controllers/subscriber_lists.controller'));
app.use('/subscribers', require('./controllers/subscribers.controller'));
app.use('/subscribers_beneficiaries', require('./controllers/subscribers_beneficiaries.controller'));
app.use('/subscribers_test', require('./controllers/subscribers_test.controller'));
app.use('/tags', require('./controllers/tags.controller'));
app.use('/to_send', require('./controllers/to_send.controller'));
app.use('/users', require('./controllers/users.controller'));
app.use('/users_permits', require('./controllers/users_permits.controller'));

// global error handler
app.use(errorHandler);

// start server
const port = config.database.env === 'production' ? (config.database.port || 80) : 5250;
app.listen(port, () => console.log('Server listening on port ' + port));