require('rootpath')();
const express = require('express');
const app = express();
const cors = require('cors');
const errorHandler = require('./_middleware/error-handler');
const config = require('./config.json');

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());

// api routes
app.use('/ads', require('./controllers/ads'));
app.use('/advisers', require('./controllers/advisers'));
app.use('/advisers_commissions', require('./controllers/advisers_commissions'));
app.use('/advisers_schedules', require('./controllers/advisers_schedules'));
app.use('/age_groups', require('./controllers/age_groups'));
app.use('/agencies', require('./controllers/agencies'));
app.use('/agencies_commissions', require('./controllers/agencies_commissions'));
app.use('/agencies_ibo', require('./controllers/agencies_ibo'));
app.use('/agencies_ibo_products', require('./controllers/agencies_ibo_products'));
app.use('/authorization_api', require('./controllers/authorization_api'));
app.use('/banners', require('./controllers/banners'));
app.use('/blog_categories', require('./controllers/blog_categories'));
app.use('/blog_tags', require('./controllers/blog_tags'));
app.use('/blogs', require('./controllers/blogs'));
app.use('/campaign_fails', require('./controllers/campaign_fails'));
app.use('/campaign_lists', require('./controllers/campaign_lists'));
app.use('/campaign_send', require('./controllers/campaign_send'));
app.use('/campaigns', require('./controllers/campaigns'));
app.use('/campaigns_push', require('./controllers/campaigns_push'));
app.use('/campaigns_push_details', require('./controllers/campaigns_push_details'));
app.use('/campaigns_push_fails', require('./controllers/campaigns_push_fails'));
app.use('/campaigns_push_lists', require('./controllers/campaigns_push_lists'));
app.use('/campaigns_push_send', require('./controllers/campaigns_push_send'));
app.use('/categories', require('./controllers/categories'));
app.use('/contacts', require('./controllers/contacts'));
app.use('/contracts', require('./controllers/contracts'));
app.use('/countries', require('./controllers/countries'));
app.use('/declaration_age_groups', require('./controllers/declaration_age_groups'));
app.use('/declaration_health', require('./controllers/declaration_health'));
app.use('/declaration_pathology', require('./controllers/declaration_pathology'));
app.use('/downloadable_files', require('./controllers/downloadable_files'));
app.use('/events', require('./controllers/events'));
app.use('/exchange_rate', require('./controllers/exchange_rate'));
app.use('/faqs', require('./controllers/faqs'));
app.use('/fee_insurances', require('./controllers/fee_insurances'));
app.use('/fee_percentages', require('./controllers/fee_percentages'));
app.use('/fee_receipts', require('./controllers/fee_receipts'));
app.use('/fees', require('./controllers/fees'));
app.use('/files', require('./controllers/files'));
app.use('/incident_files', require('./controllers/incident_files'));
app.use('/incident_service', require('./controllers/incident_service'));
app.use('/information', require('./controllers/information'));
app.use('/insurance_beneficiaries', require('./controllers/insurance_beneficiaries'));
app.use('/insurance_beneficiaries_temp', require('./controllers/insurance_beneficiaries_temp'));
app.use('/insurance_buy', require('./controllers/insurance_buy'));
app.use('/insurance_buy_declaration', require('./controllers/insurance_buy_declaration'));
app.use('/insurance_buy_declaration_temp', require('./controllers/insurance_buy_declaration_temp'));
app.use('/insurance_buy_temp', require('./controllers/insurance_buy_temp'));
app.use('/insurance_coupons', require('./controllers/insurance_coupons'));
app.use('/insurance_declaration_health', require('./controllers/insurance_declaration_health'));
app.use('/insurance_declaration_pathology', require('./controllers/insurance_declaration_pathology'));
app.use('/insurance_payment', require('./controllers/insurance_payment'));
app.use('/insurance_payment_temp', require('./controllers/insurance_payment_temp'));
app.use('/insurance_prices', require('./controllers/insurance_prices'));
app.use('/insurance_terms', require('./controllers/insurance_terms'));
app.use('/insurance_visiontravel', require('./controllers/insurance_visiontravel'));
app.use('/insurance_visiontravel_test', require('./controllers/insurance_visiontravel_test'));
app.use('/insurances', require('./controllers/insurances'));
app.use('/lists', require('./controllers/lists'));
app.use('/newsletters', require('./controllers/newsletters'));
app.use('/payment_links', require('./controllers/payment_links'));
app.use('/payment_transactions', require('./controllers/payment_transactions'));
app.use('/price_age_groups', require('./controllers/price_age_groups'));
app.use('/products', require('./controllers/products'));
app.use('/products_files', require('./controllers/products_files'));
app.use('/profiles', require('./controllers/profiles'));
app.use('/quoters', require('./controllers/quoters'));
app.use('/recover_password', require('./controllers/recover_password'));
app.use('/sections', require('./controllers/sections'));
app.use('/services', require('./controllers/services'));
app.use('/session_data', require('./controllers/session_data'));
app.use('/session_data_adviser', require('./controllers/session_data_adviser'));
app.use('/smoker_taxes', require('./controllers/smoker_taxes'));
app.use('/status', require('./controllers/status'));
app.use('/subscriber_lists', require('./controllers/subscriber_lists'));
app.use('/subscribers', require('./controllers/subscribers'));
app.use('/subscribers_beneficiaries', require('./controllers/subscribers_beneficiaries'));
app.use('/subscribers_test', require('./controllers/subscribers_test'));
app.use('/tags', require('./controllers/tags'));
app.use('/to_send', require('./controllers/to_send'));
app.use('/users', require('./controllers/users'));
app.use('/users_permits', require('./controllers/users_permits'));

// global error handler
app.use(errorHandler);

// start server
const port = config.database.env === 'production' ? (config.database.port || 80) : 5250;
app.listen(port, () => console.log('Server listening on port ' + port));